[
  {
    "title": "Looking for a roommate in Brooklyn",
    "location": "Brooklyn, NY",
    "rent": 850,
    "roomType": "Shared",
    "lifestylePreferences": ["No Smoking", "Night Owl"],
    "description": "Spacious room in a friendly household. Ideal for students or creatives. LGBTQ+ friendly.",
    "contactInfo": "123-456-7890",
    "availability": true,
    "userEmail": "jamie.brooklyn@example.com",
    "userName": "Jamie Lee"
  },
  {
    "title": "Need a roommate in downtown Chicago",
    "location": "Chicago, IL",
    "rent": 1000,
    "roomType": "Single",
    "lifestylePreferences": ["Pets", "Early Riser"],
    "description": "Private room with attached bath. Includes utilities. Dog lover preferred.",
    "contactInfo": "312-234-5678",
    "availability": true,
    "userEmail": "alex.chicago@example.com",
    "userName": "Alex Morgan"
  },
  {
    "title": "Roommate wanted in Austin with music vibe",
    "location": "Austin, TX",
    "rent": 720,
    "roomType": "Shared",
    "lifestylePreferences": ["Night Owl", "Music Friendly"],
    "description": "Live near downtown and jam every weekend. Drummers welcome!",
    "contactInfo": "512-987-6543",
    "availability": true,
    "userEmail": "sam.austin@example.com",
    "userName": "Sam Carter"
  },
  {
    "title": "Furnished room for female roommate",
    "location": "San Francisco, CA",
    "rent": 1200,
    "roomType": "Single",
    "lifestylePreferences": ["Vegetarian", "No Smoking"],
    "description": "Fully furnished room. 10 minutes walk to BART station. Quiet environment.",
    "contactInfo": "415-778-1122",
    "availability": true,
    "userEmail": "rachel.sf@example.com",
    "userName": "Rachel Green"
  },
  {
    "title": "Looking for a chill roommate in Seattle",
    "location": "Seattle, WA",
    "rent": 950,
    "roomType": "Shared",
    "lifestylePreferences": ["Pet Friendly", "Coffee Lover"],
    "description": "Big apartment, open-minded roommates. Great coffee spots nearby.",
    "contactInfo": "206-445-9987",
    "availability": false,
    "userEmail": "mike.seattle@example.com",
    "userName": "Mike Wazowski"
  },
  {
    "title": "Private room in LA - student friendly",
    "location": "Los Angeles, CA",
    "rent": 1100,
    "roomType": "Single",
    "lifestylePreferences": ["Quiet", "Early Riser"],
    "description": "Perfect for UCLA or USC students. Safe neighborhood. Study environment.",
    "contactInfo": "323-567-8901",
    "availability": true,
    "userEmail": "tina.la@example.com",
    "userName": "Tina Fey"
  },
  {
    "title": "Fun roommate wanted in Denver",
    "location": "Denver, CO",
    "rent": 800,
    "roomType": "Shared",
    "lifestylePreferences": ["Fitness Enthusiast", "Hiker"],
    "description": "Great mountain view and close to trails. Love hiking or biking? Perfect place.",
    "contactInfo": "720-654-3210",
    "availability": true,
    "userEmail": "brian.denver@example.com",
    "userName": "Brian Hill"
  },
  {
    "title": "Pet-friendly home in Atlanta",
    "location": "Atlanta, GA",
    "rent": 700,
    "roomType": "Shared",
    "lifestylePreferences": ["Dog Lover", "Laid-back"],
    "description": "Have 2 cats and a dog. Looking for someone who loves animals and is respectful.",
    "contactInfo": "404-987-1123",
    "availability": false,
    "userEmail": "lily.atlanta@example.com",
    "userName": "Lily Evans"
  },
  {
    "title": "Looking for a responsible roommate in Boston",
    "location": "Boston, MA",
    "rent": 950,
    "roomType": "Single",
    "lifestylePreferences": ["Student", "Quiet", "Non-Smoker"],
    "description": "Graduate student looking to share apartment. Clean, quiet, near campus.",
    "contactInfo": "617-555-4455",
    "availability": true,
    "userEmail": "harry.boston@example.com",
    "userName": "Harry Potter"
  }
]
